name: uslub_araby
description: "Belajar Uslub Arab"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  provider: ^6.1.2
  go_router: ^14.2.0
  flip_card: ^0.7.0
  fl_chart: ^0.68.0
  sqflite: ^2.3.3+1
  path: ^1.9.1
  path_provider: ^2.1.5
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/database_schema.sql
